// <auto-generated />
using System;
using IMDG_TaskListApp.Repos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IMDG_TaskListApp.Migrations
{
    [DbContext(typeof(TaskListContext))]
    [Migration("20190112055358_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("IMDG_TaskListApp.Models.TaskList", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("TaskId");

                    b.ToTable("TaskLists");
                });

            modelBuilder.Entity("TaskItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<DateTime>("CompletedDateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(50);

                    b.Property<int>("TaskId");

                    b.HasKey("ItemId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("TaskItem", b =>
                {
                    b.HasOne("IMDG_TaskListApp.Models.TaskList", "TaskList")
                        .WithMany("Items")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
